### ISSUE TITLE
Add deployment and configuration files

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-project#22]
@tasmo Rather than creating a new repository for deployment files (my earlier idea), I think we should add the nginx.conf and other relevant files to a subdirectory of hsg-project, `deploy`. 

I have a model in mind: https://github.com/18F/hub/tree/master/deploy. Notice that nginx, init.d, and logrotate.d are all stored in `deploy/etc`. 

I realize we have two different nginx.conf files - one for each front end server - so we may need some additional subdirectories. Or perhaps you have a better idea for handling these parameters?

**Comment by joewiz** [comment]
Please also store the jetty.xml, conf.xml, etc. files inside `deploy` too.

**Comment by tasmo** [comment]
@joewiz We didn't change the jetty.xml in favour just to change the `/etc/keystore` with the imported Letsencrypt certs.

**Comment by joewiz** [comment]
@tasmo I see, then there's no need to store jetty.xml - only files modified from default values.

**Comment by tasmo** [comment]
nginx.config upload is done
