### ISSUE TITLE
Prepare for migration to eXist 3.x

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-project#29]
When eXist 3.1 is released, I would like to update hsg-project from the custom build of eXist 3.0RC1 circa May 2016 to the current release version of eXist, most importantly because the old version is incompatible with tei-publisher-lib, which our revised CMS apps are built on. 

Changes I envision to build.xml and build.properties:
- Pull eXide, shared-resources, and tei-simple-pm directly from the public-repo, instead of cloning and building them ourselves locally. 
- Add tei-publisher-lib to the list of apps to be installed via the public-repo.
- Remove monex from the list of apps to be installed via the public-repo.

I've started a branch with some updated build files.

Manual steps I'm following to migrate:

1. Check out the new `migrate-to-exist-3.0` branch
2. Delete the following directories from the repos directory: eXide, shared-resources, tei-simple-pm, and, if present, tei-publishing-lib
3. Copy production.instance.password from local.build.properties, then select (in oXygen's External Tools menu) "Enter server credentials", pasting in the copied password. This will refresh the list of cloned repos in local.build.properties.

@tuurma Could you please confer with the other @HistoryAtState/existsolutions devs and ponder what will be needed to migrate the hsg servers to eXist 3.x?

**Comment by joewiz** [comment]
FYI - The migration of history.state.gov to eXist 3.x began earlier this morning and is still underway.  Please hold off on uploading files to history.state.gov until you have further updates.  Commits to github may proceed, but you'll just need to remember to upload changed files once the migration is complete.

**Comment by joewiz** [comment]
Please feel free to resume uploading to hsg. The migration encountered some hiccups and didn't complete last Thursday, so it's rescheduled for some day later this week. @tasmo and @tuurma, do you have a new day planned for the migration?

**Comment by tasmo** [comment]
@joewiz @tuurma Yes, this thursday.

**Comment by joewiz** [comment]
@tasmo Sounds good. 

Everyone, please plan a similar freeze of uploads to hsg for Thursday.
